# Generated by Django 6.0.7 on 2026-07-29 06:17

import django.db.models.deletion
import django.utils.timezone
import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('password_hash', models.CharField(max_length=255, verbose_name='パスワード（ハッシュ）')),
                ('must_change_password', models.BooleanField(default=True, verbose_name='初回パスワード変更が必要か')),
                ('otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='ワンタイムパスワードの有効期限')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='core.customer', verbose_name='顧客')),
            ],
            options={
                'verbose_name': '会員アカウント',
                'verbose_name_plural': '会員アカウント',
            },
        ),
        migrations.CreateModel(
            name='GuestInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('token', models.CharField(default=members.models._random_token, max_length=64, unique=True, verbose_name='トークン')),
                ('used', models.BooleanField(default=False, verbose_name='使用済みフラグ')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='発行日時')),
                ('created_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guest_invitation', to='core.customer', verbose_name='このトークンで作成された顧客')),
            ],
            options={
                'verbose_name': 'ゲスト招待',
                'verbose_name_plural': 'ゲスト招待',
            },
        ),
    ]
